# Generated by Django 6.0.7 on 2026-07-09 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('mobile_without_country_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('lead_owner', models.EmailField(blank=True, max_length=254)),
                ('crm_status', models.CharField(blank=True, choices=[('GOOD_LEAD_FOLLOW_UP', 'GOOD_LEAD_FOLLOW_UP'), ('DID_NOT_CONNECT', 'DID_NOT_CONNECT'), ('BAD_LEAD', 'BAD_LEAD'), ('SALE_DONE', 'SALE_DONE')], max_length=30)),
                ('crm_note', models.TextField(blank=True)),
                ('data_source', models.CharField(blank=True, choices=[('leads_on_demand', 'leads_on_demand'), ('meridian_tower', 'meridian_tower'), ('eden_park', 'eden_park'), ('varah_swamy', 'varah_swamy'), ('sarjapur_plots', 'sarjapur_plots')], max_length=50)),
                ('possession_time', models.CharField(blank=True, max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='importer.upload')),
            ],
        ),
    ]
