# Generated by Django 6.0.7 on 2026-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlead',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
