# Generated by Django 6.0.7 on 2026-07-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_crmlead_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
