# Generated by Django 6.0.7 on 2026-07-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_crmlead_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
